#!/bin/bash
#
#    micro-cluster-add-all-nodes - add all local nodes in the micro-cluster
#    Copyright (C) 2014 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

auth_points="$(maas-cli list)"

if [ "$auth_points" == "" ]; then
	echo "You must first log in with sudo maas-cli login <maas-key>"
	exit 1
fi

set -ex

export AMT_PASSWORD="Password1+"
export VNC_PASSWORD="$AMT_PASSWORD"

apt-get install -y wsmancli amtterm
nodelist=nodelists/`hostname`-nodelist

ips=$(grep "^lease " /var/lib/maas/dhcp/dhcpd.leases | awk '{print $2}' | sort -u)
for ip in $ips; do
	mac=$(grep -A20 "^lease $ip {" /var/lib/maas/dhcp/dhcpd.leases | grep -B20 "}" | grep -m1 "hardware ethernet " | sed -e "s/.* //" -e "s/;//")
	echo "$ip $mac"
	# Enable remote VNC to each node
	# set the vnc password
	# Password MUST BE *exactly 8 characters long and contain 1 capital letter, a number, and a special character!!!
	wsman put http://intel.com/wbem/wscim/1/ips-schema/1/IPS_KVMRedirectionSettingData -h $ip -P 16992 -u admin -p ${AMT_PASSWORD} -k RFBPassword=${VNC_PASSWORD}
	# enable KVM redirection to port 5900
	wsman put http://intel.com/wbem/wscim/1/ips-schema/1/IPS_KVMRedirectionSettingData -h $ip -P 16992 -u admin -p ${AMT_PASSWORD} -k Is5900PortEnabled=true
	# disable opt-in policy
	wsman put http://intel.com/wbem/wscim/1/ips-schema/1/IPS_KVMRedirectionSettingData -h $ip -P 16992 -u admin -p ${AMT_PASSWORD} -k OptInPolicy=false
	# disable session timeout
	wsman put http://intel.com/wbem/wscim/1/ips-schema/1/IPS_KVMRedirectionSettingData -h $ip -P 16992 -u admin -p ${AMT_PASSWORD} -k SessionTimeout=0
	# enable KVM
	wsman invoke -a RequestStateChange http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_KVMRedirectionSAP -h ${ip} -P 16992 -u admin -p ${AMT_PASSWORD} -k RequestedState=2
	# Add the node to MAAS
	# dap: added hostname parameter which pulls from a file named
	# `hostname`-nodelist in the nodelists subdirectory
	maas-cli admin nodes new architecture=amd64 power_type=amt mac_addresses=$mac power_parameters_power_address=$ip power_parameters_power_pass=$AMT_PASSWORD hostname="`grep $mac $nodelist | awk '{print $2}'`"
	(yes | amttool $ip powerdown) || true
	sleep 1
	yes | run-one-until-success amttool $ip powerup pxe
done
