#!/bin/bash

# Only run this as root 
if [ $EUID -ne 0 ]
then
	echo Execute as root or with \"sudo $0\"
	exit 1
fi

# Set up structure
if [ $(mount | grep /dev/sdb1 | wc -l) -ne 1 ]
then
	echo Mounting /dev/sdb1 under /srv...
	mount /dev/sdb1 /srv || echo Error mounting /dev/sdb1 && exit 1
    echo YOU MUST ADD /dev/sdb1 TO FSTAB TO ENSURE IT MOUNTS EVERY TIME WE BOOT!!!
fi

mkdir -p /mnt/mirror/precise || echo Error creating /mnt/mirror/precise && exit 1

# install charm-tools if not already there
PKGS=charm-tools apt-mirror
for pkg in $PKGS; do
    if [ $(dpkg -l | grep $pkg | grep ^ii) -ne 0 ]
    then
	    echo Installing $pkg
	    apt-get -y install $pkg || echo Error installing $pkg && exit 1
    fi
done

# run apt-mirror to mirror the archives
if [ -f /etc/apt/mirrors.list ]; then
    apr-mirror /etc/apt/mirrors.list || echo ERROR SYNCING MIRRORS && exit 1
else
    echo ERROR mirrors.list not found
fi

# grab the charms into /mnt/mirror/precise
cd /srv/charmstore/precise
charm getall

# make charms trustified
cd /srv/charmstore
cp -a precise/ trusty/

# done
cd -
echo Done.
