#!/bin/bash

if [ $(mount | grep /dev/sdb1 | wc -l) -ne 1 ]
then
	echo Mounting /dev/sdb1 under /mnt...
	mount /dev/sdb1 /mnt || (echo Error mounting /dev/sdb1 && exit 1)
fi

mkdir -p /mnt/mirror || (echo Error creating /mnt/mirror && exit 1)

rsync -avP archive.ubuntu.com::ubuntu /mnt/mirror/
