#!/bin/sh

set -e
set -x

# Configure NAT and IP forwarding, giving slave NUCs external network access through the master
# Note that this should NOT be used when we're simulating a closed network

echo 1 > /proc/sys/net/ipv4/ip_forward
echo "net.ipv4.ip_forward=1" > /etc/sysctl.conf.d/10-maas-ip-forward

sysctl net.ipv4.ip_forward=1
# Not needed if using MAAS proxy
#sudo iptables -t nat -A POSTROUTING -s 10.0.0.1/24 -o eth0 -j MASQUERADE
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
iptables -A FORWARD -i eth0 -o em1 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i em1 -o eth0 -j ACCEPT
