#!/bin/sh

set -e
set -x

if [ "$(id -u)" != "0" ]; then
    echo "Must be run with sudo or by root"
    return 127
fi

# Seed package with proper values
apt-get install debconf-utils
debconf-set-selections etc/debconf-selections

# Install all of MAAS, and add amtterm for amttool power management of NUCs
apt-get install -y maas maas-cluster-controller amtterm

maas createsuperuser --username admin --email maas-admin@example.com || true

sed -i -e /^RELEASES=/d -e /^ARCHES=/d /etc/maas/import_pxe_files

cat > /etc/network/interfaces <<EOF
auto lo
iface lo inet loopback

# The interface to the internal network.
auto em1
iface em1 inet static
    address 10.0.0.1
    netmask 255.255.255.0
    broadcast 10.0.0.255

# USB NIC; connect to LAN.
auto eth0
iface eth0 inet dhcp

EOF

service networking restart

cat >> /etc/maas/import_pxe_files <<EOF
RELEASES="precise trusty"
ARCHES="amd64/generic i386/generic"
EOF

run-this-one maas-import-pxe-files
