#!/bin/sh

# This script assumes that it's being run as root. We should probably 
# check for that in a future revision.

set -e
set -x

# Configure NAT and IP forwarding, giving slave NUCs external network access 
# through the master.

# Note that this script assumes no existing iptables rules. If you do have
# any, they will be deleted. 

# Enable IP forwarding and save for next boot
echo 1 > /proc/sys/net/ipv4/ip_forward
echo "net.ipv4.ip_forward=1" > /etc/sysctl.conf.d/10-maas-ip-forward
#sysctl net.ipv4.ip_forward=1

# Some things use the MAAS proxy - some things don't. So turn on NAT.
# First we blow away the existing postrouting/NAT config.

/sbin/iptables -F POSTROUTING
/sbin/iptables -F -t nat

/sbin/iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
/sbin/iptables -A FORWARD -i eth0 -o em1 -m state --state RELATED,ESTABLISHED -j ACCEPT
/sbin/iptables -A FORWARD -i em1 -o eth0 -j ACCEPT

# Ubuntu for some reason does not install requirements for iptables 
# to be persisted across reboots. So let's fix that.

/usr/bin/apt-get update
/usr/bin/apt-get install iptables-persistent

/sbin/iptables-save > /etc/iptables/rules.v4


