#!/bin/bash

if [ "$(id -u)" != "0" ]; then
    echo "Must be run with sudo or by root"
    exit 127
fi

set -e

# Seed package with proper values
apt-get install debconf-utils
debconf-set-selections etc/debconf-selections

# Install all of MAAS, and add amtterm for amttool power management of NUCs
apt-get install -y maas maas-cluster-controller amtterm

# Just run createadmin, since we can feed it a password
#maas createsuperuser --username root --email maas-root@example.com || true
maas createadmin --username admin --email maas-admin@example.com --password="Password1+" || true

sed -i -e /^RELEASES=/d -e /^ARCHES=/d /etc/maas/import_pxe_files

for i in 0..5; do
	echo "Checking eth$i..."
	if [ ifconfig eth$i ]; then
		echo -n 'found!'
		iface="eth$i"
	fi
done

iface=""

for i in {0..5}; do
	echo -n "Checking eth$i...";
	if ifconfig eth$i > /dev/null 2>&1; then
		echo 'found!';
		iface="eth$i";
	else
		echo
	fi
done

if [ "$iface" == "" ]; then
	echo "Unable to detech eth interface"
	exit 1
fi

cat > /etc/network/interfaces <<EOF
auto lo
iface lo inet loopback

# The interface to the internal network.
auto em1
iface em1 inet static
    address 10.0.0.1
    netmask 255.255.255.0
    broadcast 10.0.0.255

# USB NIC; connect to LAN.
auto $iface
iface $iface inet dhcp

EOF

service networking restart

cat >> /etc/maas/import_pxe_files <<EOF
RELEASES="precise trusty"
ARCHES="amd64/generic i386/generic"
EOF

run-this-one maas-import-pxe-files
