#!/bin/sh

set -e
set -x

# Configure NAT and IP forwarding, giving slave NUCs external network access through the master
# Note that this should NOT be used when we're simulating a closed network

sudo sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
echo net.ipv4.ip_forward=1 | sudo tee -a /etc/sysctl.conf
sudo sysctl net.ipv4.ip_forward=1
sudo iptables -t nat -A POSTROUTING -s 10.0.0.1/24 -i eth0 -j MASQUERADE
