default: openstack
environments:
  openstack:
    type: openstack
    control-bucket: __UUID__
    admin-secret: Password1+
    auth-url: __AUTH_URL__
    region: RegionOne
    image-metadata-url: http://10.0.0.1/images/
    username: admin
    password: Password1+
    tenant-name: admin
    use-floating-ip: true
