#!/bin/sh

set -e

PKG="orangebox"
webserver="apache2"

case "$1" in
        configure)
                a2ensite archive
                a2ensite ubuntu-cloud
                invoke-rc.d $webserver reload
        ;;
        abort-upgrade|abort-remove|abort-deconfigure)
        ;;
        *)
                echo "postinst called with unknown argument \`$1'" >&2
                exit 1
        ;;
esac

#DEBHELPER#

exit 0
