#!/bin/sh

set -e
set -x

PKG="orange-box"
RETRY=120

. /usr/lib/orange-box/inc/common

setup_maas_admin() {
	# Configure the MAAS admin user
	# Sadly, there's no way to test if the user has been created already,
	# so ignore errors for idempotence
	maas-region-admin createadmin --username admin --email maas-admin@example.com --password="admin" 2>/dev/null || true
}

setup_maas_networking() {
	. /etc/maas/maas_cluster.conf
	APIKEY=$(maas-region-admin apikey --username admin)
	maas login admin $MAAS_URL $APIKEY
	count=0
	while ! maas admin node-group-interfaces list $CLUSTER_UUID >/dev/null 2>&1; do
		count=$((count+1))
		sleep 1
		if [ $count -gt $RETRY ]; then
			error "[maas admin node-group-interfaces list] failed [$RETRY] times"
		fi
	done
	internal_interface=$(route -n | grep "^10\.14\.4\." | sed -e "s/.* //")
	maas admin node-group-interface update $CLUSTER_UUID $internal_interface ip_range_high=10.14.4.20 ip_range_low=10.14.4.250 management=2 broadcast_ip=10.14.4.255 router_ip=10.14.4.1
	#orange-box-setup-nat $internal_interface $external_interface
}

setup_external_drive() {
	# External drive must be:
	#	a) on /dev/sdb
	#	b) partitioned into 1 big partition
	#	c) ext4 formatted
	if [ -b /dev/sdb1 ] && ! grep -qs '^/dev/sdb1' /etc/fstab; then
		echo "/dev/sdb1	/srv	ext4	defaults	1 1" >> /etc/fstab
	fi
	umount /dev/sdb1 || true
	mount -a
}

setup_local_mirror() {
	# Set up the local mirror
	a2ensite archive
	a2ensite ubuntu-cloud
	a2dissite 000-default
	invoke-rc.d apache2 restart
}

setup_boot_resources() {
	# Use our boot resources as found on the external storage
	if [ -e /var/lib/maas/boot-resources ] && [ ! -h /var/lib/maas/boot-resources ] && [ -d /srv/boot-resources ]; then
		mv -f /var/lib/maas/boot-resources /var/lib/maas/boot-resources.orig
		ln -sf /srv/boot-resources /var/lib/maas/
	fi
	# Start importing boot resources in the background
	run-this-one maas-import-pxe-files &
}

setup_ssh_keys() {
	if [ ! -e /home/ubuntu/.ssh/id_rsa ]; then
		su -l ubuntu -c "ssh-keygen -N '' -f /home/ubuntu/.ssh/id_rsa"
	fi
	maas admin sshkeys new key="$(cat /home/ubuntu/.ssh/id_rsa.pub)" || true
}

setup_juju() {
	mkdir -p /home/ubuntu/.juju
	cat >/home/ubuntu/.juju/environments.yaml <<EOF
default: maas
environments:
    maas:
        type: maas
        maas-server: 'http://10.14.4.1/MAAS/'
        maas-oauth: '$APIKEY'
        default-series: precise
        authorized-keys-path: /home/ubuntu/.ssh/id_rsa.pub
        admin-secret: 'admin'
EOF
	sudo chown -R ubuntu:ubuntu /home/ubuntu/.juju
}

ensure_running() {
	job="$1"
	count=1
	while true; do
		if (status $job | grep -qs "start/running,"); then
			break
		fi
		invoke-rc.d $job start
		sleep 1
		count=$((count+1))
		if [ $count -gt $RETRY ]; then
			error "[$job] refused to start [$RETRY] times"
		fi
	done
}

ensure_running_maas() {
	ensure_running maas-region-celery
	ensure_running maas-cluster-celery
	ensure_running maas-txlongpoll
	ensure_running maas-pserv
	ensure_running maas-dhcp-server
}

setup_all_nodes() {
	# Ensure that pxe and dhcp are running
	ensure_running_maas
	orange-box-add-all-nodes
}

case "$1" in
	configure)
		setup_boot_resources
		setup_maas_admin
		setup_maas_networking
		setup_external_drive
		setup_local_mirror
		setup_ssh_keys
		setup_juju
		setup_all_nodes
	;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	*)
		echo "postinst called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0
