#!/bin/sh

set -e

webserver="apache2"

case "$1" in
	remove)
		for i in archive ubuntu-cloud; do
			if [ -e "/etc/apache2/sites-enabled/${i}.conf" ]; then
				a2dissite $i
			fi
		done
		invoke-rc.d $webserver reload
		rm -f /var/log/orange-box-mirror.log
		rm -rf /etc/maas
	;;
esac

#DEBHELPER#

exit 0
