#!/bin/sh
set -e

preflight_checks() {
	if [ "$(id -u ubuntu)" != "1000" ]; then
		echo "ERROR: Read the docs; a proper OrangeBox setup requires the default user to be [ubuntu]" 1>&2
		exit 1
	fi
	case $(hostname) in
		OrangeBox*)
			true
		;;
		*)
			echo "ERROR: Read the docs; a OrangeBox setup requires the hostname to be in the form [OrangeBox*]" 1>&2
			exit 1
		;;
	esac
	# TODO: Check that the AMTs are on static IPs
	# TODO: Check dual hard drives, which one is which
}

setup_debconf() {
	echo "debconf maas/default-maas-url string 10.14.4.1" | debconf-set-selections -
	echo "debconf maas-cluster-controller/maas-url string http://10.14.4.1/MAAS" | debconf-set-selections -
	echo "debconf maas/installation-note boolean true" | debconf-set-selections -
	echo "debconf iptables-persistent/autosave_v4 boolean true" | debconf-set-selections -
	echo "debconf iptables-persistent/autosave_v6 boolean true" | debconf-set-selections -
}

setup_networking() {
	# Set up the two network interfaces
	local Iface Destination Gateway Flags RefCnt Use Metric Mask MTU Window IRTT
	while read Iface Destination Gateway Flags RefCnt Use Metric Mask MTU Window IRTT; do
		[ "$Mask" = "00000000" ] && break
	done < /proc/net/route
	external_interface="$Iface"
	for interface in $(ifconfig -a -s | grep -v ^Iface | awk '{print $1}'); do
		case "$interface" in
			lo|br*)
				continue
			;;
			$external_interface)
				continue
			;;
			*)
				internal_interface="$interface"
				break
			;;
		esac
	done
	# Set a sane default
	[ -z "$internal_interface" ] && internal_interface=eth0
	default_mac=$(ifconfig "$internal_interface" | grep "^$internal_interface" | sed -e "s/.*HWaddr //")
	# Tell NetworkManager to piss off
	sed -i -e "/^unmanaged-devices=mac:$default_mac$/d" /etc/NetworkManager/NetworkManager.conf
	cat >>/etc/NetworkManager/NetworkManager.conf <<EOF
[keyfile]
unmanaged-devices=mac:$default_mac
EOF
	invoke-rc.d network-manager restart
        cat >/etc/network/interfaces <<EOF
auto lo
iface lo inet loopback

auto $internal_interface
iface $internal_interface inet static

auto br0
iface br0 inet static
        address 10.14.4.1
        netmask 255.255.255.0
        broadcast 10.14.4.255
	bridge_ports $internal_interface
	bridge_stp off
	bridge_fd 0
	bridge_maxwait 0
EOF
	ifdown $internal_interface || true
	ifdown br0 || true
	ifup $internal_interface
	ifup br0
        # Wait a moment for the network to normalize
        sleep 5
}

setup_external_drive() {
	# External drive must be:
	#       a) on /dev/sdb
	#       b) partitioned into 1 big partition
	#       c) ext4 formatted
	if [ -b /dev/sdb1 ] && ! grep -qs '^/dev/sdb1' /etc/fstab; then
		echo "/dev/sdb1 /srv    ext4    defaults        1 1" >> /etc/fstab
	fi
	umount /dev/sdb1 || true
	mount -a
}


preflight_checks
setup_external_drive
setup_debconf
setup_networking

#DEBHELPER#

exit 0
